/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.farmsys.UI;

import com.farmsys.Entity.NhanVien;
import com.farmsys.Entity.NhatKy;
import com.farmsys.Helper.MsgBox;
import com.farmsys.Helper.XImage;
import com.farmsys.dao.CongViecDAO;
import com.farmsys.dao.NhanVienDAO;
import com.farmsys.dao.NhatKyDAO;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.print.PrinterException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class NhatKyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NhatKyJPanel
     */
    public NhatKyJPanel() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        TheNVJDialog = new javax.swing.JDialog();
        pnlTong = new javax.swing.JPanel();
        imageAvatar = new com.farmsys.Helper.ImageAvatar();
        lblTenNV = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblVaiTro = new javax.swing.JLabel();
        lblGioiTinh = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtVaiTro = new javax.swing.JTextField();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        txtTenNV = new javax.swing.JTextField();
        buttonGroup3 = new javax.swing.ButtonGroup();
        pnlNhatKy = new javax.swing.JPanel();
        txttimkiem = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhatKy = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        TheNVJDialog.setTitle("Thẻ nhân viên");
        TheNVJDialog.setMinimumSize(new java.awt.Dimension(472, 223));
        TheNVJDialog.setUndecorated(true);
        TheNVJDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTong.setBackground(new java.awt.Color(255, 255, 255));
        pnlTong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTongMouseClicked(evt);
            }
        });

        imageAvatar.setBackground(new java.awt.Color(255, 255, 255));
        imageAvatar.setForeground(new java.awt.Color(255, 255, 255));

        lblTenNV.setText("Tên");

        lblEmail.setText("Email:");

        lblVaiTro.setText("Vai Trò:");

        lblGioiTinh.setText("Giới Tính: ");

        txtEmail.setEditable(false);
        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEmail.setText("jTextField1");

        txtVaiTro.setEditable(false);
        txtVaiTro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtVaiTro.setText("jTextField1");

        buttonGroup3.add(rdoNam);
        rdoNam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoNam.setText("Nam");
        rdoNam.setEnabled(false);

        buttonGroup3.add(rdoNu);
        rdoNu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoNu.setText("Nữ");
        rdoNu.setEnabled(false);

        txtTenNV.setEditable(false);
        txtTenNV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTenNV.setText("jTextField1");

        javax.swing.GroupLayout pnlTongLayout = new javax.swing.GroupLayout(pnlTong);
        pnlTong.setLayout(pnlTongLayout);
        pnlTongLayout.setHorizontalGroup(
            pnlTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTongLayout.createSequentialGroup()
                        .addGroup(pnlTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTongLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(pnlTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlTongLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlTongLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoNam, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(rdoNu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnlTongLayout.setVerticalGroup(
            pnlTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTongLayout.createSequentialGroup()
                .addGroup(pnlTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTongLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imageAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTongLayout.createSequentialGroup()
                        .addGroup(pnlTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTongLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(pnlTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlTongLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(pnlTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(pnlTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoNam)
                    .addComponent(rdoNu))
                .addContainerGap())
        );

        TheNVJDialog.getContentPane().add(pnlTong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 220));

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1083, 750));
        setPreferredSize(new java.awt.Dimension(1083, 750));

        pnlNhatKy.setBackground(new java.awt.Color(255, 255, 255));
        pnlNhatKy.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NHẬT KÝ CÔNG VIỆC", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        pnlNhatKy.setMinimumSize(new java.awt.Dimension(1083, 749));
        pnlNhatKy.setName(""); // NOI18N
        pnlNhatKy.setPreferredSize(new java.awt.Dimension(1083, 749));
        pnlNhatKy.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txttimkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttimkiemKeyPressed(evt);
            }
        });
        pnlNhatKy.add(txttimkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 970, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Tìm kiếm:");
        pnlNhatKy.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, 30));

        tblNhatKy.setAutoCreateRowSorter(true);
        tblNhatKy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên công việc", "Tên Cây", "Tên Giàn", "Chi tiết công việc", "Người tạo", "Nhân viên", "Bắt đầu", "Kết thúc", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhatKy.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblNhatKy.setMinimumSize(new java.awt.Dimension(750, 480));
        tblNhatKy.setRowHeight(40);
        tblNhatKy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhatKyMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhatKy);

        pnlNhatKy.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 1040, 510));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlNhatKy.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 610, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNhatKy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlNhatKy, javax.swing.GroupLayout.PREFERRED_SIZE, 728, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txttimkiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimkiemKeyPressed
//        this.fillTableNhatKyByTenCV();
//        this.fillTableNhatKyByTenCay();
        this.fillTableNhatKyByTenNV();


    }//GEN-LAST:event_txttimkiemKeyPressed

    private void tblNhatKyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhatKyMouseClicked
        if (evt.getClickCount() == 2) {
            TheNVJDialog.setVisible(true);
            this.row = tblNhatKy.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tblNhatKyMouseClicked

    private void pnlTongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTongMouseClicked
        TheNVJDialog.setVisible(false);
    }//GEN-LAST:event_pnlTongMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.print();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog TheNVJDialog;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private com.farmsys.Helper.ImageAvatar imageAvatar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JLabel lblVaiTro;
    private javax.swing.JPanel pnlNhatKy;
    private javax.swing.JPanel pnlTong;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTable tblNhatKy;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtVaiTro;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables
    int row = -1;
    NhatKyDAO nkdao = new NhatKyDAO();
    CongViecDAO cvdao = new CongViecDAO();
    NhanVienDAO nvdao = new NhanVienDAO();

    private void init() {
        this.fillTableNhatALL();
        this.TheNVJDialog.setLocationRelativeTo(null);
        new Timer(60000, (ActionEvent e) -> {
            this.fillTableNhatALL();
        }).start();
    }

    private void fillTableNhatALL() {
        DefaultTableModel model = (DefaultTableModel) tblNhatKy.getModel();
        model.setRowCount(0);
        List<NhatKy> list = nkdao.selectAll();
        for (NhatKy nk : list) {
            String status = trangThai(nk);
            model.addRow(new Object[]{
                nk.getStt(),
                nk.getTenCV(),
                nk.getTenCay(),
                nk.getTenGian(),
                nk.getChiTiet(),
                nk.getNguoiTao(),
                nk.getNhanVien(),
                nk.getNgayBatDau(),
                nk.getNgayKetThuc(),
                status
            });
        }
    }

    private void fillTableNhatKyByTenCay() {
        DefaultTableModel model = (DefaultTableModel) tblNhatKy.getModel();
        model.setRowCount(0);
        String TimKiem = txttimkiem.getText();
        List<NhatKy> list = nkdao.selectByTenCay(TimKiem);
        for (NhatKy nk : list) {
            String status = trangThai(nk);
            model.addRow(new Object[]{
                nk.getStt(),
                nk.getTenCV(),
                nk.getTenCay(),
                nk.getTenGian(),
                nk.getChiTiet(),
                nk.getNguoiTao(),
                nk.getNhanVien(),
                nk.getNgayBatDau(),
                nk.getNgayKetThuc(),
                status
            });
        }
    }

    private void fillTableNhatKyByTenCV() {
        DefaultTableModel model = (DefaultTableModel) tblNhatKy.getModel();
        model.setRowCount(0);
        String TimKiem = txttimkiem.getText();
        List<NhatKy> list = nkdao.selectByTenCay(TimKiem);
        for (NhatKy nk : list) {
            String status = trangThai(nk);
            model.addRow(new Object[]{
                nk.getStt(),
                nk.getTenCV(),
                nk.getTenCay(),
                nk.getTenGian(),
                nk.getChiTiet(),
                nk.getNguoiTao(),
                nk.getNhanVien(),
                nk.getNgayBatDau(),
                nk.getNgayKetThuc(),
                status
            });
        }
    }

    private void fillTableNhatKyByTenNV() {
        DefaultTableModel model = (DefaultTableModel) tblNhatKy.getModel();
        model.setRowCount(0);
        String TimKiem = txttimkiem.getText();
        List<NhatKy> list = nkdao.selectByTenNV(TimKiem);
        for (NhatKy nk : list) {
            String status = trangThai(nk);
            model.addRow(new Object[]{
                nk.getStt(),
                nk.getTenCV(),
                nk.getTenCay(),
                nk.getTenGian(),
                nk.getChiTiet(),
                nk.getNguoiTao(),
                nk.getNhanVien(),
                nk.getNgayBatDau(),
                nk.getNgayKetThuc(),
                status
            });
        }
    }

    private String trangThai(NhatKy nk) {
        String status = null;
        status = switch (nk.getTrangThai()) {
            case 0 ->
                "Chưa nhận";
            case 1 ->
                "Đang làm";
            case 2 ->
                "Từ chối";
            case 3 ->
                "Hoàn thành";
            case 4 ->
                "Hoàn thành muộn";
            default ->
                "Đang bán";
        };
        return status;
    }

    void print() {
        try {
            Boolean print = tblNhatKy.print();
            if (print) {
                MsgBox.alert(this, "Đã xuất file PDF");
            } else {

            }
        } catch (PrinterException ex) {
            Logger.getLogger(NhatKyJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    JFileChooser fileChooser = new JFileChooser();

    private void edit() {
        String manv = (String) tblNhatKy.getValueAt(this.row, 6);
        String name = txtTenNV.getText();
        NhanVien nv = nvdao.selectById(manv);
        this.setForm(nv);

    }

    private void setForm(NhanVien nv) {
        txtTenNV.setText(nv.getHoTen());
        txtEmail.setText(nv.getEmail());
        if (nv.isVaiTro() == true) {
            txtVaiTro.setText("Trưởng phòng");
        } else {
            txtVaiTro.setText("Nhân viên");
        }
        if (nv.isGioiTinh() == true) {
            rdoNam.setSelected(true);
        } else {
            rdoNu.setSelected(true);
        }
        if (nv.getHinh() != null) {
            imageAvatar.setToolTipText(nv.getHinh());
            ImageIcon icon = XImage.read(nv.getHinh()); // Lấy địa chỉ của file Icon
            //Chuyển Icon sang image và điều chỉnh kích thước
            Image scaleIcon = icon.getImage().getScaledInstance(imageAvatar.getWidth(), imageAvatar.getHeight(), Image.SCALE_DEFAULT);
            imageAvatar.setImage(new javax.swing.ImageIcon(scaleIcon));
        }

    }
}
