/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.farmsys.UI;

import com.farmsys.Helper.HandleAPI;
import com.farmsys.data.JsonResult;

/**
 *
 * @author NguyenTrung
 */
public class WeatherJDialog extends javax.swing.JDialog {

    /**
     * Creates new form WeatherJDialog
     *
     * @param parent
     * @param modal
     */
    public WeatherJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlweather = new javax.swing.JPanel();
        lb_date = new javax.swing.JLabel();
        lb_city = new javax.swing.JLabel();
        lb_nation = new javax.swing.JLabel();
        lb_nhietDo = new javax.swing.JLabel();
        lb_apXuat = new javax.swing.JLabel();
        lb_cloud = new javax.swing.JLabel();
        lb_doAm = new javax.swing.JLabel();
        lblnext = new javax.swing.JLabel();
        lblpre = new javax.swing.JLabel();
        lb_weather = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlweather.setBackground(new java.awt.Color(255, 255, 255));
        pnlweather.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlweatherMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlweatherMouseExited(evt);
            }
        });

        lb_date.setText("Ngày :");

        lb_city.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lb_city.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/city_16px.png"))); // NOI18N
        lb_city.setText(":");

        lb_nation.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lb_nation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/Globe.png"))); // NOI18N
        lb_nation.setText(":");

        lb_nhietDo.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lb_nhietDo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/temperature_16px.png"))); // NOI18N
        lb_nhietDo.setText(":");

        lb_apXuat.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lb_apXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/pressure_16px.png"))); // NOI18N
        lb_apXuat.setText(":");

        lb_cloud.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lb_cloud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/cloud_16px.png"))); // NOI18N
        lb_cloud.setText(":");

        lb_doAm.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lb_doAm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/hygrometer_16px.png"))); // NOI18N
        lb_doAm.setText(":");

        lblnext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/forward_16px.png"))); // NOI18N
        lblnext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblnextMouseClicked(evt);
            }
        });

        lblpre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/back_16px.png"))); // NOI18N
        lblpre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblpreMouseClicked(evt);
            }
        });

        lb_weather.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 11)); // NOI18N
        lb_weather.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/weather_16px.png"))); // NOI18N
        lb_weather.setText(":");

        javax.swing.GroupLayout pnlweatherLayout = new javax.swing.GroupLayout(pnlweather);
        pnlweather.setLayout(pnlweatherLayout);
        pnlweatherLayout.setHorizontalGroup(
            pnlweatherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlweatherLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlweatherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_nation, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_date, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_city, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_apXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addGroup(pnlweatherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_nhietDo, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addGroup(pnlweatherLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblpre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblnext))
                    .addComponent(lb_cloud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_doAm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(123, 123, 123))
            .addGroup(pnlweatherLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(lb_weather, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlweatherLayout.setVerticalGroup(
            pnlweatherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlweatherLayout.createSequentialGroup()
                .addGroup(pnlweatherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlweatherLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(pnlweatherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblnext)
                            .addComponent(lblpre)))
                    .addComponent(lb_date, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlweatherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_nhietDo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlweatherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_city, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_doAm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlweatherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_cloud, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_apXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lb_weather, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlweather, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlweather, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblnextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblnextMouseClicked
        idx = idx == 39 ? idx : idx + 1;
        setThoiTiet();
    }//GEN-LAST:event_lblnextMouseClicked

    private void lblpreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpreMouseClicked
        idx = idx == 0 ? idx : idx - 1;
        setThoiTiet();
    }//GEN-LAST:event_lblpreMouseClicked

    private void pnlweatherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlweatherMouseClicked

    }//GEN-LAST:event_pnlweatherMouseClicked

    private void pnlweatherMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlweatherMouseExited

    }//GEN-LAST:event_pnlweatherMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WeatherJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WeatherJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WeatherJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WeatherJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WeatherJDialog dialog = new WeatherJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lb_apXuat;
    private javax.swing.JLabel lb_city;
    private javax.swing.JLabel lb_cloud;
    private javax.swing.JLabel lb_date;
    private javax.swing.JLabel lb_doAm;
    private javax.swing.JLabel lb_nation;
    private javax.swing.JLabel lb_nhietDo;
    private javax.swing.JLabel lb_weather;
    private javax.swing.JLabel lblnext;
    private javax.swing.JLabel lblpre;
    private javax.swing.JPanel pnlweather;
    // End of variables declaration//GEN-END:variables

    private JsonResult result;
    private int idx = 0;

    private void init() {
        result = HandleAPI.getJsonData((String) "Saigon");
        setThoiTiet();
    }

    void setThoiTiet() {
        String date = " Ngày: " + result.getList()[idx].getDt_txt();
        String city = " Thành phố: " + result.getCity().getName();
        String nation = " Quốc gia: " + result.getCity().getCountry();
        String weath = " Weather: " + result.getList()[idx].getWeather()[0].getDescription();
        String nhietDo = " Nhiệt độ: " + result.getList()[idx].getMain().getTemp() + " độ C";
        String apXuat = " Áp xuất: " + result.getList()[idx].getMain().getPresure() + " Pa";
        String doAm = " Độ ẩm: " + result.getList()[idx].getMain().getHumidity() + " %";
        String clouds = " Mây: " + result.getList()[idx].getClouds().getAll() + " %";

        lb_apXuat.setText(apXuat);
        lb_city.setText(city);
        lb_cloud.setText(clouds);
        lb_date.setText(date);
        lb_doAm.setText(doAm);
        lb_nation.setText(nation);
        lb_nhietDo.setText(nhietDo);
        lb_weather.setText(weath);
    }
}
