/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.farmsys.UI;

import com.farmsys.Helper.HandleAPI;
import com.farmsys.data.JsonResult;
import javax.swing.ImageIcon;

/**
 *
 * @author NguyenTrung
 */
public class WeatherJDialog extends javax.swing.JDialog {

    /**
     * Creates new form WeatherJDialog
     *
     * @param parent
     * @param modal
     */
    public WeatherJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlweather = new javax.swing.JPanel();
        lbldate = new javax.swing.JLabel();
        lblcity = new javax.swing.JLabel();
        lblnhietdo = new javax.swing.JLabel();
        lblapxuat = new javax.swing.JLabel();
        lblcloud = new javax.swing.JLabel();
        lbldoam = new javax.swing.JLabel();
        lblnext = new javax.swing.JLabel();
        lblpre = new javax.swing.JLabel();
        lblweather = new javax.swing.JLabel();
        lblwind = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setModal(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlweather.setBackground(new java.awt.Color(51, 51, 51));
        pnlweather.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlweatherMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlweatherMouseExited(evt);
            }
        });
        pnlweather.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbldate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbldate.setForeground(new java.awt.Color(255, 255, 255));
        lbldate.setText(":");
        pnlweather.add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 40));

        lblcity.setBackground(new java.awt.Color(204, 204, 204));
        lblcity.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblcity.setForeground(new java.awt.Color(255, 255, 255));
        lblcity.setText(":");
        pnlweather.add(lblcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 210, 40));

        lblnhietdo.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lblnhietdo.setForeground(new java.awt.Color(255, 255, 255));
        lblnhietdo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnhietdo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/icons8_rain_cloud_30px_1.png"))); // NOI18N
        lblnhietdo.setText("27 C");
        pnlweather.add(lblnhietdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 40));

        lblapxuat.setBackground(new java.awt.Color(204, 204, 204));
        lblapxuat.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblapxuat.setForeground(new java.awt.Color(255, 255, 255));
        lblapxuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblapxuat.setText(":");
        pnlweather.add(lblapxuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 120, 44));

        lblcloud.setBackground(new java.awt.Color(204, 204, 204));
        lblcloud.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblcloud.setForeground(new java.awt.Color(255, 255, 255));
        lblcloud.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcloud.setText(":");
        pnlweather.add(lblcloud, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 120, 43));

        lbldoam.setBackground(new java.awt.Color(204, 204, 204));
        lbldoam.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbldoam.setForeground(new java.awt.Color(255, 255, 255));
        lbldoam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldoam.setText(":");
        pnlweather.add(lbldoam, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 110, 44));

        lblnext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/forward_16px.png"))); // NOI18N
        lblnext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblnextMouseClicked(evt);
            }
        });
        pnlweather.add(lblnext, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 40, -1));

        lblpre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/back_16px.png"))); // NOI18N
        lblpre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblpreMouseClicked(evt);
            }
        });
        pnlweather.add(lblpre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        lblweather.setBackground(new java.awt.Color(204, 204, 204));
        lblweather.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        lblweather.setForeground(new java.awt.Color(255, 255, 255));
        lblweather.setText("rain");
        pnlweather.add(lblweather, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 210, 40));

        lblwind.setBackground(new java.awt.Color(204, 204, 204));
        lblwind.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblwind.setForeground(new java.awt.Color(255, 255, 255));
        lblwind.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblwind.setText(":");
        pnlweather.add(lblwind, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 120, 44));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/farmsys/icons/rain.jpeg"))); // NOI18N
        pnlweather.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 620, 300));

        getContentPane().add(pnlweather, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 612, 288));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblnextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblnextMouseClicked
        idx = idx == 39 ? idx : idx + 1;
        setThoiTiet();
    }//GEN-LAST:event_lblnextMouseClicked

    private void lblpreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpreMouseClicked
        idx = idx == 0 ? idx : idx - 1;
        setThoiTiet();
    }//GEN-LAST:event_lblpreMouseClicked

    private void pnlweatherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlweatherMouseClicked

    }//GEN-LAST:event_pnlweatherMouseClicked

    private void pnlweatherMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlweatherMouseExited

    }//GEN-LAST:event_pnlweatherMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WeatherJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WeatherJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WeatherJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WeatherJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WeatherJDialog dialog = new WeatherJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel lblapxuat;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lblcloud;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbldoam;
    private javax.swing.JLabel lblnext;
    private javax.swing.JLabel lblnhietdo;
    private javax.swing.JLabel lblpre;
    private javax.swing.JLabel lblweather;
    private javax.swing.JLabel lblwind;
    private javax.swing.JPanel pnlweather;
    // End of variables declaration//GEN-END:variables

    private JsonResult result;
    private int idx = 0;

    private void init() {
        result = HandleAPI.getJsonData((String) "Saigon");
        setThoiTiet();
    }

    void setThoiTiet() {
        String date = " Ngày: " + result.getList()[idx].getDt_txt();
        String city = " Thành phố: " + result.getCity().getName();
        String weath = result.getList()[idx].getWeather()[0].getDescription();
        String nhietDo = result.getList()[idx].getMain().getTemp() + " °";
        String apXuat = " Áp xuất: " + result.getList()[idx].getMain().getPresure() + " Pa";
        String doAm = " Độ ẩm: " + result.getList()[idx].getMain().getHumidity() + " %";
        String clouds = " Mây: " + result.getList()[idx].getClouds().getAll() + " %";
        String wind = "Gió: " + result.getList()[idx].getWind().getSpeed() + " km/h";

        lblapxuat.setText(apXuat);
        lblcity.setText(city);
        lblcloud.setText(clouds);
        lbldate.setText(date);
        lbldoam.setText(doAm);
        lblnhietdo.setText(nhietDo);
        lblweather.setText(weath);
        lblwind.setText(wind);

        String text = lblweather.getText();
        if (text.contains("clouds")) {
            lblnhietdo.setIcon(new ImageIcon("src\\com\\farmsys\\icons\\cloud_30px.png"));
            background.setIcon(new ImageIcon("src\\com\\farmsys\\icons\\may.jpg"));
        } else if (text.contains("sun")) {
            lblnhietdo.setIcon(new ImageIcon("src\\com\\farmsys\\icons\\icons8_summer_30px.png"));
            background.setIcon(new ImageIcon("src\\com\\farmsys\\icons\\nangsaigon.jpg"));
        } else if (text.contains("rain")) {
            lblnhietdo.setIcon(new ImageIcon("src\\com\\farmsys\\icons\\icons8_rain_cloud_30px_1.png"));
            background.setIcon(new ImageIcon("src\\com\\farmsys\\icons\\rain.jpg"));
        }
    }
}
